[directory]
truncate_to_repo = false
read_only = ' '
truncation_length = 10
truncation_symbol = '…/'

[directory.substitutions]
"~/Documents" = ""
"~/Downloads" = ""
"~/Music" = ""
"~/Pictures" = ""
"~/Git" = ""

[git_branch]
symbol = " "

[git_metrics]
disabled = false

[git_status]
stashed = ''

[rust]
symbol = ""

[gcloud]
disabled = true

# 

# 
# 
# 
