#
# Zsh configuration file
#
# Author: Sylvain Lebresne <lebresne@gmail.com>
#


# Zplug modules

source ~/.zplug/init.zsh

zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"

zplug "mafredri/zsh-async"
zplug "sindresorhus/pure", use:pure.zsh, as:theme

zplug "joel-porquet/zsh-dircolors-solarized"

zplug "caarlos0/git-add-remote"

zplug "hkupty/ssh-agent"
zplug "srijanshetty/zsh-pip-completion"

zplug "zdharma/fast-syntax-highlighting", defer:2

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# Options

# silence please
setopt nobeep
setopt noflowcontrol

# Case insensitive completions
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' '+m:{A-Z}={a-z}'

# Aliases

alias ls='ls --color=auto -F'

# Exports

export HISTSIZE=100000
export HISTFILE=$HOME/.history
export SAVEHIST=$HISTSIZE

export EDITOR=vim
export VISUAL=vim

# i = smart case in searches
# F = exit immediately if fit one screen
# R = AINSI color support
# X = suppress alternate screen
export LESS=iFRX

export PATH=$HOME/.bin:$PATH

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Load specific local changes if any
[ -f $HOME/.zsh.local ] && source $HOME/.zsh.local
